version: "3.8"

services:
  db:
    image: mariadb:10
    container_name: nc-tristan-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /disk/data-01/tristan/data-nc/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=
  app:
    image: nextcloud
    container_name: nc-tristan-app
    restart: unless-stopped
    ports:
      - 23001:80
    volumes:
      - /disk/data-01/tristan/data-nc/nc:/var/www/html
      - ./config.php:/var/www/html/config/config.php
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=

networks:
  default:
    name: jeff
